"""empty message

Revision ID: ccd831868f73
Revises: 72c9f07b4496
Create Date: 2021-09-09 17:34:01.967985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd831868f73'
down_revision = '72c9f07b4496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('gall_num', sa.Integer(), nullable=False),
    sa.Column('gall_writer', sa.String(length=30), nullable=True),
    sa.Column('gall_date', sa.Date(), nullable=False),
    sa.Column('gall_title', sa.String(length=100), nullable=False),
    sa.Column('gall_content', sa.String(length=1500), nullable=False),
    sa.Column('gall_img', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['gall_writer'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gall_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery')
    # ### end Alembic commands ###
